'use strict'

export const SE_CLIENT_ID = '4805'
export const SE_KEY = 'JBGpilme4Le5JbqbJEawQA(('
export const SE_CHANNEL_URL = 'http://mgreystone.github.io/blizzard.codetest/blank.txt'
export const SE_API_PREFIX = 'https://api.stackexchange.com'
export const SE_SITE = 'stackoverflow.com'
export const SE_FILTER_QUESTIONS = 'vqc7K'
export const SE_FILTER_QUESTION_DETAILS = 'YGk-WepcCWi*0'
export const SE_FILTER_USER_PROFILE = '*kcHPrjmpCN'
export const SE_FILTER_USER_BADGES = '0TxEu28'
export const SE_FILTER_ANSWERS_LIST = '8G3Nb9Is'
export const SE_FILTER_BADGES = 'vqc7K'
